<?php
/**
 * Implements hook_menu().
 *
 * Adds the charting result page on each Webform node.
 */
function oc_bookmarks_restore_menu() {
 $items = array();
 $items['oc/bookmarks/restore'] = array(
    'page callback' => 'oc_bookmarks_restore_run', // Render HTML
    'description' => 'Attempts to restore a users bookmarks after migrate to 5.5',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content')
   );
  return $items;
}
function oc_bookmarks_restore_run()
{
    global $user;
    if(isset($user->mail) && !empty($user->mail))
    {
        $query = new EntityFieldQuery();
        $query->entityCondition('entity_type', 'user')
        ->propertyCondition('mail', $user->mail);

        $result = $query->execute();
        $num_updated = 0;
        if (isset($result['node'])) {
          $All_Users = array_keys($result['node']);
          
          foreach($All_Users as $uid)
          {
              if($user->uid != $uid)
              {
                  echo "updating bookmarks:" . $uid . "\n";
                 $num_updated += oc_bookmarks_restore_update_bookmarks($uid,$user->uid);
              }
          }
        }
        echo "Restored:" . $num_updated . " for:". $user->uid;
    }
}
function oc_bookmarks_restore_update_bookmarks($old_uid,$new_uid)
{
    $query = db_select('user', 'n')
      ->condition('n.uid', $old_uid, '=')
      ->fields('n', array('uid'))
      ->execute();
      return $num = $query->rowCount();
    /*
    $num_updated = db_update('flag_content')
    ->fields(array(
      'uid' => $new_uid,
    ))
    ->condition('uid',$old_uid, '=')
    ->execute();
    
    return $num_updated;*/
}